// @flow
export const CREATE_TOPIC = 'CREATE_TOPIC';
export const CREATE_TOPIC_BEGIN = 'CREATE_TOPIC_BEGIN';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const DELETE_TOPIC = 'DELETE_TOPIC';
export const DELETE_TOPIC_BEGIN = 'DELETE_TOPIC_BEGIN';
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
export const DELETE_TOPIC_FAILURE = 'DELETE_TOPIC_FAILURE';
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPICS_BEGIN = 'FETCH_TOPICS_BEGIN';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAILURE = 'FETCH_TOPICS_FAILURE';
export const BEGIN_TOPIC_TITLE_CHANGE = 'BEGIN_TOPIC_TITLE_CHANGE';
export const BEGIN_TOPIC_BODY_CHANGE = 'BEGIN_TOPIC_BODY_CHANGE';
