// flow-typed signature: 7da3f3a32c9902044ad443bf2bb7e232
// flow-typed version: <<STUB>>/axe-core_v^3.3.1/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axe-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axe-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axe-core/axe' {
  declare module.exports: any;
}

declare module 'axe-core/axe.min' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/chrome-debugging-protocol/axe-cdp' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/jasmine/karma.conf' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/jasmine/spec/a11y' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/jest_react/link' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/jest_react/link.test' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/jest_react/test-helpers' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/mocha/karma.conf' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/phantomjs/axe-phantom' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/puppeteer/axe-puppeteer' {
  declare module.exports: any;
}

declare module 'axe-core/doc/examples/test-examples' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/abstractrole' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/allowed-attr' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/aria-allowed-role' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/aria-hidden-body' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/errormessage' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/has-widget-role' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/implicit-role-fallback' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/invalidrole' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/no-implicit-explicit-label' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/required-attr' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/required-children' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/required-parent' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/unsupportedattr' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/unsupportedrole' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/valid-attr-value' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/valid-attr' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/aria/valid-scrollable-semantics' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/color/color-contrast' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/color/link-in-text-block' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/forms/autocomplete-appropriate' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/forms/autocomplete-valid' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/forms/fieldset-after' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/forms/fieldset' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/forms/group-labelledby-after' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/forms/group-labelledby' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/accesskeys-after' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/accesskeys' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/focusable-content' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/focusable-disabled' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/focusable-element' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/focusable-no-name' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/focusable-not-tabbable' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/landmark-is-top-level' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/page-has-elm-after' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/page-has-elm' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/page-no-duplicate' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/keyboard/tabindex' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/label/alt-space-value' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/label/duplicate-img-label' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/label/explicit' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/label/help-same-as-label' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/label/hidden-explicit-label' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/label/implicit' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/label/label-content-name-mismatch' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/label/multiple-label' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/label/title-only' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/landmarks/landmark-is-unique-after' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/landmarks/landmark-is-unique' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/language/has-lang' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/language/valid-lang' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/language/xml-lang-mismatch' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/lists/dlitem' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/lists/listitem' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/lists/only-dlitems' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/lists/only-listitems' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/lists/structured-dlitems' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/media/caption' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/media/description' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/media/frame-tested' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/mobile/css-orientation-lock' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/mobile/meta-viewport-scale' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/header-present' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/heading-order-after' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/heading-order' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/internal-link-present' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/landmark' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/meta-refresh' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/p-as-heading' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/region-after' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/region' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/skip-link' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/unique-frame-title-after' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/navigation/unique-frame-title' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/parsing/duplicate-id-after' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/parsing/duplicate-id' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/aria-label' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/aria-labelledby' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/avoid-inline-spacing' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/button-has-visible-text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/doc-has-title' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/exists' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/has-alt' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/has-visible-text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/is-on-screen' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/non-empty-alt' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/non-empty-if-present' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/non-empty-title' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/non-empty-value' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/role-none' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/shared/role-presentation' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/caption-faked' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/has-caption' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/has-summary' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/has-th' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/headers-visible-text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/html5-scope' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/same-caption-summary' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/scope-value' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/td-has-header' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/td-headers-attr' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/th-has-data-cells' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/tables/th-single-row-column' {
  declare module.exports: any;
}

declare module 'axe-core/lib/checks/visibility/hidden-content' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/arialabel-text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/arialabelledby-text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/attributes' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/get-element-unallowed-roles' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/get-owned-virtual' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/get-role' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/is-accessible-ref' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/is-aria-role-allowed-on-element' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/is-unsupported-role' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/label-virtual' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/named-from-contents' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/roles' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/aria/validate-attr-value' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/color/center-point-of-rect' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/color/contrast' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/color/element-has-image' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/color/element-is-distinct' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/color/get-background-color' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/color/get-foreground-color' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/color/get-own-background-color' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/color/incomplete-data' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/color' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/elements-below-floating' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/find-elms-in-context' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/find-up' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/get-composed-parent' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/get-element-by-reference' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/get-element-coordinates' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/get-root-node' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/get-scroll-offset' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/get-tabbable-elements' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/get-viewport-size' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/has-content-virtual' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/idrefs' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/is-focusable' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/is-hidden-with-css' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/is-html5' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/is-in-text-block' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/is-node' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/is-offscreen' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/is-skip-link' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/is-visible' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/is-visual-content' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/shadow-elements-from-point' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/visually-contains' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/dom/visually-overlaps' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/forms' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/forms/is-aria-combobox' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/forms/is-aria-listbox' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/forms/is-aria-range' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/forms/is-aria-textbox' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/forms/is-native-select' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/forms/is-native-textbox' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/matches/attributes' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/matches/condition' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/matches/from-definition' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/matches/from-function' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/matches/from-primative' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/matches/node-name' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/matches/properties' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/get-all-cells' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/get-cell-position' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/get-headers' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/get-scope' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/is-column-header' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/is-data-cell' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/is-data-table' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/is-header' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/is-row-header' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/to-grid' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/table/traverse' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/accessible-text-virtual' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/form-control-value' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/is-human-interpretable' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/is-valid-autocomplete' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/label-text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/label-virtual' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/native-element-types' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/native-text-alternative' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/native-text-methods' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/sanitize' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/subtree-text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/title-text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/unicode' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/unsupported' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/text/visible-virtual' {
  declare module.exports: any;
}

declare module 'axe-core/lib/commons/utils' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/base/audit' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/base/cache' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/base/check-result' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/base/check' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/base/context' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/base/rule-result' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/base/rule' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/base/virtual-node' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/constants' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/imports' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/log' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/cleanup-plugins' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/configure' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/get-rules' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/load' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/plugins' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/reporter' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/reset' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/run-rules' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/run-virtual-rule' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/public/run' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/helpers/failure-summary' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/helpers/get-environment-data' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/helpers/incomplete-fallback-msg' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/helpers' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/helpers/process-aggregate' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/na' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/no-passes' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/raw-env' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/raw' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/v1' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/reporters/v2' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/aggregate' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/aggregateChecks' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/aggregateNodeResults' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/aggregateResult' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/are-styles-set' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/check-helper' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/clone' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/collect-results-from-frames' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/contains' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/css-parser' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/dq-element' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/element-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/escape-selector' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/extend-meta-data' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/finalize-result' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/find-by' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/flattened-tree' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-all-checks' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-base-lang' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-check-option' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-friendly-uri-end' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-node-attributes' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-root-node' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-scroll' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-selector' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-stylesheet-factory' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/get-xpath' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/inject-style' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/is-hidden' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/is-html-element' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/is-shadow-root' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/is-xhtml' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/merge-results' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/node-sorter' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/parse-crossorigin-stylesheet' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/parse-sameorigin-stylesheet' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/parse-stylesheet' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/performance-timer' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/pollyfills' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/preload-cssom' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/preload' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/publish-metadata' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/qsa' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/queue' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/respondable' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/rule-should-run' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/scroll-state' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/select' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/to-array' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/token-list' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/uuid' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/valid-input-type' {
  declare module.exports: any;
}

declare module 'axe-core/lib/core/utils/valid-langs' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/aria-allowed-attr-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/aria-allowed-role-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/aria-dpub-role-fallback-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/aria-form-field-name-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/aria-has-attr-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/aria-hidden-focus-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/autocomplete-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/bypass-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/color-contrast-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/data-table-large-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/data-table-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/duplicate-id-active-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/duplicate-id-aria-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/duplicate-id-misc-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/frame-title-has-text' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/heading-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/inserted-into-focus-order-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/label-content-name-mismatch-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/label-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/landmark-has-body-context' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/landmark-unique-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/layout-table-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/link-in-text-block-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/no-role-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/not-html-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/p-as-heading-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/role-not-button-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/scrollable-region-focusable-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/skip-link-matches' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/window-is-top' {
  declare module.exports: any;
}

declare module 'axe-core/lib/rules/xml-lang-mismatch-matches' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axe-core/axe.js' {
  declare module.exports: $Exports<'axe-core/axe'>;
}
declare module 'axe-core/axe.min.js' {
  declare module.exports: $Exports<'axe-core/axe.min'>;
}
declare module 'axe-core/doc/examples/chrome-debugging-protocol/axe-cdp.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/chrome-debugging-protocol/axe-cdp'>;
}
declare module 'axe-core/doc/examples/jasmine/karma.conf.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/jasmine/karma.conf'>;
}
declare module 'axe-core/doc/examples/jasmine/spec/a11y.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/jasmine/spec/a11y'>;
}
declare module 'axe-core/doc/examples/jest_react/link.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/jest_react/link'>;
}
declare module 'axe-core/doc/examples/jest_react/link.test.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/jest_react/link.test'>;
}
declare module 'axe-core/doc/examples/jest_react/test-helpers.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/jest_react/test-helpers'>;
}
declare module 'axe-core/doc/examples/mocha/karma.conf.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/mocha/karma.conf'>;
}
declare module 'axe-core/doc/examples/phantomjs/axe-phantom.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/phantomjs/axe-phantom'>;
}
declare module 'axe-core/doc/examples/puppeteer/axe-puppeteer.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/puppeteer/axe-puppeteer'>;
}
declare module 'axe-core/doc/examples/test-examples.js' {
  declare module.exports: $Exports<'axe-core/doc/examples/test-examples'>;
}
declare module 'axe-core/lib/checks/aria/abstractrole.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/abstractrole'>;
}
declare module 'axe-core/lib/checks/aria/allowed-attr.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/allowed-attr'>;
}
declare module 'axe-core/lib/checks/aria/aria-allowed-role.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/aria-allowed-role'>;
}
declare module 'axe-core/lib/checks/aria/aria-hidden-body.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/aria-hidden-body'>;
}
declare module 'axe-core/lib/checks/aria/errormessage.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/errormessage'>;
}
declare module 'axe-core/lib/checks/aria/has-widget-role.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/has-widget-role'>;
}
declare module 'axe-core/lib/checks/aria/implicit-role-fallback.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/implicit-role-fallback'>;
}
declare module 'axe-core/lib/checks/aria/invalidrole.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/invalidrole'>;
}
declare module 'axe-core/lib/checks/aria/no-implicit-explicit-label.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/no-implicit-explicit-label'>;
}
declare module 'axe-core/lib/checks/aria/required-attr.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/required-attr'>;
}
declare module 'axe-core/lib/checks/aria/required-children.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/required-children'>;
}
declare module 'axe-core/lib/checks/aria/required-parent.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/required-parent'>;
}
declare module 'axe-core/lib/checks/aria/unsupportedattr.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/unsupportedattr'>;
}
declare module 'axe-core/lib/checks/aria/unsupportedrole.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/unsupportedrole'>;
}
declare module 'axe-core/lib/checks/aria/valid-attr-value.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/valid-attr-value'>;
}
declare module 'axe-core/lib/checks/aria/valid-attr.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/valid-attr'>;
}
declare module 'axe-core/lib/checks/aria/valid-scrollable-semantics.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/aria/valid-scrollable-semantics'>;
}
declare module 'axe-core/lib/checks/color/color-contrast.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/color/color-contrast'>;
}
declare module 'axe-core/lib/checks/color/link-in-text-block.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/color/link-in-text-block'>;
}
declare module 'axe-core/lib/checks/forms/autocomplete-appropriate.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/forms/autocomplete-appropriate'>;
}
declare module 'axe-core/lib/checks/forms/autocomplete-valid.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/forms/autocomplete-valid'>;
}
declare module 'axe-core/lib/checks/forms/fieldset-after.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/forms/fieldset-after'>;
}
declare module 'axe-core/lib/checks/forms/fieldset.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/forms/fieldset'>;
}
declare module 'axe-core/lib/checks/forms/group-labelledby-after.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/forms/group-labelledby-after'>;
}
declare module 'axe-core/lib/checks/forms/group-labelledby.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/forms/group-labelledby'>;
}
declare module 'axe-core/lib/checks/keyboard/accesskeys-after.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/accesskeys-after'>;
}
declare module 'axe-core/lib/checks/keyboard/accesskeys.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/accesskeys'>;
}
declare module 'axe-core/lib/checks/keyboard/focusable-content.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/focusable-content'>;
}
declare module 'axe-core/lib/checks/keyboard/focusable-disabled.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/focusable-disabled'>;
}
declare module 'axe-core/lib/checks/keyboard/focusable-element.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/focusable-element'>;
}
declare module 'axe-core/lib/checks/keyboard/focusable-no-name.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/focusable-no-name'>;
}
declare module 'axe-core/lib/checks/keyboard/focusable-not-tabbable.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/focusable-not-tabbable'>;
}
declare module 'axe-core/lib/checks/keyboard/landmark-is-top-level.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/landmark-is-top-level'>;
}
declare module 'axe-core/lib/checks/keyboard/page-has-elm-after.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/page-has-elm-after'>;
}
declare module 'axe-core/lib/checks/keyboard/page-has-elm.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/page-has-elm'>;
}
declare module 'axe-core/lib/checks/keyboard/page-no-duplicate.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/page-no-duplicate'>;
}
declare module 'axe-core/lib/checks/keyboard/tabindex.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/keyboard/tabindex'>;
}
declare module 'axe-core/lib/checks/label/alt-space-value.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/label/alt-space-value'>;
}
declare module 'axe-core/lib/checks/label/duplicate-img-label.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/label/duplicate-img-label'>;
}
declare module 'axe-core/lib/checks/label/explicit.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/label/explicit'>;
}
declare module 'axe-core/lib/checks/label/help-same-as-label.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/label/help-same-as-label'>;
}
declare module 'axe-core/lib/checks/label/hidden-explicit-label.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/label/hidden-explicit-label'>;
}
declare module 'axe-core/lib/checks/label/implicit.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/label/implicit'>;
}
declare module 'axe-core/lib/checks/label/label-content-name-mismatch.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/label/label-content-name-mismatch'>;
}
declare module 'axe-core/lib/checks/label/multiple-label.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/label/multiple-label'>;
}
declare module 'axe-core/lib/checks/label/title-only.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/label/title-only'>;
}
declare module 'axe-core/lib/checks/landmarks/landmark-is-unique-after.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/landmarks/landmark-is-unique-after'>;
}
declare module 'axe-core/lib/checks/landmarks/landmark-is-unique.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/landmarks/landmark-is-unique'>;
}
declare module 'axe-core/lib/checks/language/has-lang.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/language/has-lang'>;
}
declare module 'axe-core/lib/checks/language/valid-lang.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/language/valid-lang'>;
}
declare module 'axe-core/lib/checks/language/xml-lang-mismatch.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/language/xml-lang-mismatch'>;
}
declare module 'axe-core/lib/checks/lists/dlitem.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/lists/dlitem'>;
}
declare module 'axe-core/lib/checks/lists/listitem.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/lists/listitem'>;
}
declare module 'axe-core/lib/checks/lists/only-dlitems.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/lists/only-dlitems'>;
}
declare module 'axe-core/lib/checks/lists/only-listitems.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/lists/only-listitems'>;
}
declare module 'axe-core/lib/checks/lists/structured-dlitems.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/lists/structured-dlitems'>;
}
declare module 'axe-core/lib/checks/media/caption.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/media/caption'>;
}
declare module 'axe-core/lib/checks/media/description.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/media/description'>;
}
declare module 'axe-core/lib/checks/media/frame-tested.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/media/frame-tested'>;
}
declare module 'axe-core/lib/checks/mobile/css-orientation-lock.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/mobile/css-orientation-lock'>;
}
declare module 'axe-core/lib/checks/mobile/meta-viewport-scale.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/mobile/meta-viewport-scale'>;
}
declare module 'axe-core/lib/checks/navigation/header-present.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/header-present'>;
}
declare module 'axe-core/lib/checks/navigation/heading-order-after.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/heading-order-after'>;
}
declare module 'axe-core/lib/checks/navigation/heading-order.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/heading-order'>;
}
declare module 'axe-core/lib/checks/navigation/internal-link-present.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/internal-link-present'>;
}
declare module 'axe-core/lib/checks/navigation/landmark.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/landmark'>;
}
declare module 'axe-core/lib/checks/navigation/meta-refresh.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/meta-refresh'>;
}
declare module 'axe-core/lib/checks/navigation/p-as-heading.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/p-as-heading'>;
}
declare module 'axe-core/lib/checks/navigation/region-after.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/region-after'>;
}
declare module 'axe-core/lib/checks/navigation/region.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/region'>;
}
declare module 'axe-core/lib/checks/navigation/skip-link.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/skip-link'>;
}
declare module 'axe-core/lib/checks/navigation/unique-frame-title-after.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/unique-frame-title-after'>;
}
declare module 'axe-core/lib/checks/navigation/unique-frame-title.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/navigation/unique-frame-title'>;
}
declare module 'axe-core/lib/checks/parsing/duplicate-id-after.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/parsing/duplicate-id-after'>;
}
declare module 'axe-core/lib/checks/parsing/duplicate-id.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/parsing/duplicate-id'>;
}
declare module 'axe-core/lib/checks/shared/aria-label.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/aria-label'>;
}
declare module 'axe-core/lib/checks/shared/aria-labelledby.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/aria-labelledby'>;
}
declare module 'axe-core/lib/checks/shared/avoid-inline-spacing.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/avoid-inline-spacing'>;
}
declare module 'axe-core/lib/checks/shared/button-has-visible-text.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/button-has-visible-text'>;
}
declare module 'axe-core/lib/checks/shared/doc-has-title.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/doc-has-title'>;
}
declare module 'axe-core/lib/checks/shared/exists.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/exists'>;
}
declare module 'axe-core/lib/checks/shared/has-alt.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/has-alt'>;
}
declare module 'axe-core/lib/checks/shared/has-visible-text.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/has-visible-text'>;
}
declare module 'axe-core/lib/checks/shared/is-on-screen.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/is-on-screen'>;
}
declare module 'axe-core/lib/checks/shared/non-empty-alt.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/non-empty-alt'>;
}
declare module 'axe-core/lib/checks/shared/non-empty-if-present.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/non-empty-if-present'>;
}
declare module 'axe-core/lib/checks/shared/non-empty-title.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/non-empty-title'>;
}
declare module 'axe-core/lib/checks/shared/non-empty-value.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/non-empty-value'>;
}
declare module 'axe-core/lib/checks/shared/role-none.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/role-none'>;
}
declare module 'axe-core/lib/checks/shared/role-presentation.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/shared/role-presentation'>;
}
declare module 'axe-core/lib/checks/tables/caption-faked.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/caption-faked'>;
}
declare module 'axe-core/lib/checks/tables/has-caption.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/has-caption'>;
}
declare module 'axe-core/lib/checks/tables/has-summary.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/has-summary'>;
}
declare module 'axe-core/lib/checks/tables/has-th.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/has-th'>;
}
declare module 'axe-core/lib/checks/tables/headers-visible-text.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/headers-visible-text'>;
}
declare module 'axe-core/lib/checks/tables/html5-scope.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/html5-scope'>;
}
declare module 'axe-core/lib/checks/tables/same-caption-summary.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/same-caption-summary'>;
}
declare module 'axe-core/lib/checks/tables/scope-value.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/scope-value'>;
}
declare module 'axe-core/lib/checks/tables/td-has-header.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/td-has-header'>;
}
declare module 'axe-core/lib/checks/tables/td-headers-attr.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/td-headers-attr'>;
}
declare module 'axe-core/lib/checks/tables/th-has-data-cells.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/th-has-data-cells'>;
}
declare module 'axe-core/lib/checks/tables/th-single-row-column.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/tables/th-single-row-column'>;
}
declare module 'axe-core/lib/checks/visibility/hidden-content.js' {
  declare module.exports: $Exports<'axe-core/lib/checks/visibility/hidden-content'>;
}
declare module 'axe-core/lib/commons/aria/arialabel-text.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/arialabel-text'>;
}
declare module 'axe-core/lib/commons/aria/arialabelledby-text.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/arialabelledby-text'>;
}
declare module 'axe-core/lib/commons/aria/attributes.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/attributes'>;
}
declare module 'axe-core/lib/commons/aria/get-element-unallowed-roles.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/get-element-unallowed-roles'>;
}
declare module 'axe-core/lib/commons/aria/get-owned-virtual.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/get-owned-virtual'>;
}
declare module 'axe-core/lib/commons/aria/get-role.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/get-role'>;
}
declare module 'axe-core/lib/commons/aria/index' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria'>;
}
declare module 'axe-core/lib/commons/aria/index.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria'>;
}
declare module 'axe-core/lib/commons/aria/is-accessible-ref.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/is-accessible-ref'>;
}
declare module 'axe-core/lib/commons/aria/is-aria-role-allowed-on-element.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/is-aria-role-allowed-on-element'>;
}
declare module 'axe-core/lib/commons/aria/is-unsupported-role.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/is-unsupported-role'>;
}
declare module 'axe-core/lib/commons/aria/label-virtual.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/label-virtual'>;
}
declare module 'axe-core/lib/commons/aria/named-from-contents.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/named-from-contents'>;
}
declare module 'axe-core/lib/commons/aria/roles.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/roles'>;
}
declare module 'axe-core/lib/commons/aria/validate-attr-value.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/aria/validate-attr-value'>;
}
declare module 'axe-core/lib/commons/color/center-point-of-rect.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/color/center-point-of-rect'>;
}
declare module 'axe-core/lib/commons/color/contrast.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/color/contrast'>;
}
declare module 'axe-core/lib/commons/color/element-has-image.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/color/element-has-image'>;
}
declare module 'axe-core/lib/commons/color/element-is-distinct.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/color/element-is-distinct'>;
}
declare module 'axe-core/lib/commons/color/get-background-color.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/color/get-background-color'>;
}
declare module 'axe-core/lib/commons/color/get-foreground-color.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/color/get-foreground-color'>;
}
declare module 'axe-core/lib/commons/color/get-own-background-color.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/color/get-own-background-color'>;
}
declare module 'axe-core/lib/commons/color/incomplete-data.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/color/incomplete-data'>;
}
declare module 'axe-core/lib/commons/color/index' {
  declare module.exports: $Exports<'axe-core/lib/commons/color'>;
}
declare module 'axe-core/lib/commons/color/index.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/color'>;
}
declare module 'axe-core/lib/commons/dom/elements-below-floating.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/elements-below-floating'>;
}
declare module 'axe-core/lib/commons/dom/find-elms-in-context.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/find-elms-in-context'>;
}
declare module 'axe-core/lib/commons/dom/find-up.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/find-up'>;
}
declare module 'axe-core/lib/commons/dom/get-composed-parent.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/get-composed-parent'>;
}
declare module 'axe-core/lib/commons/dom/get-element-by-reference.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/get-element-by-reference'>;
}
declare module 'axe-core/lib/commons/dom/get-element-coordinates.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/get-element-coordinates'>;
}
declare module 'axe-core/lib/commons/dom/get-root-node.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/get-root-node'>;
}
declare module 'axe-core/lib/commons/dom/get-scroll-offset.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/get-scroll-offset'>;
}
declare module 'axe-core/lib/commons/dom/get-tabbable-elements.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/get-tabbable-elements'>;
}
declare module 'axe-core/lib/commons/dom/get-viewport-size.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/get-viewport-size'>;
}
declare module 'axe-core/lib/commons/dom/has-content-virtual.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/has-content-virtual'>;
}
declare module 'axe-core/lib/commons/dom/idrefs.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/idrefs'>;
}
declare module 'axe-core/lib/commons/dom/index' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom'>;
}
declare module 'axe-core/lib/commons/dom/index.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom'>;
}
declare module 'axe-core/lib/commons/dom/is-focusable.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/is-focusable'>;
}
declare module 'axe-core/lib/commons/dom/is-hidden-with-css.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/is-hidden-with-css'>;
}
declare module 'axe-core/lib/commons/dom/is-html5.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/is-html5'>;
}
declare module 'axe-core/lib/commons/dom/is-in-text-block.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/is-in-text-block'>;
}
declare module 'axe-core/lib/commons/dom/is-node.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/is-node'>;
}
declare module 'axe-core/lib/commons/dom/is-offscreen.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/is-offscreen'>;
}
declare module 'axe-core/lib/commons/dom/is-skip-link.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/is-skip-link'>;
}
declare module 'axe-core/lib/commons/dom/is-visible.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/is-visible'>;
}
declare module 'axe-core/lib/commons/dom/is-visual-content.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/is-visual-content'>;
}
declare module 'axe-core/lib/commons/dom/shadow-elements-from-point.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/shadow-elements-from-point'>;
}
declare module 'axe-core/lib/commons/dom/visually-contains.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/visually-contains'>;
}
declare module 'axe-core/lib/commons/dom/visually-overlaps.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/dom/visually-overlaps'>;
}
declare module 'axe-core/lib/commons/forms/index' {
  declare module.exports: $Exports<'axe-core/lib/commons/forms'>;
}
declare module 'axe-core/lib/commons/forms/index.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/forms'>;
}
declare module 'axe-core/lib/commons/forms/is-aria-combobox.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/forms/is-aria-combobox'>;
}
declare module 'axe-core/lib/commons/forms/is-aria-listbox.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/forms/is-aria-listbox'>;
}
declare module 'axe-core/lib/commons/forms/is-aria-range.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/forms/is-aria-range'>;
}
declare module 'axe-core/lib/commons/forms/is-aria-textbox.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/forms/is-aria-textbox'>;
}
declare module 'axe-core/lib/commons/forms/is-native-select.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/forms/is-native-select'>;
}
declare module 'axe-core/lib/commons/forms/is-native-textbox.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/forms/is-native-textbox'>;
}
declare module 'axe-core/lib/commons/index' {
  declare module.exports: $Exports<'axe-core/lib/commons'>;
}
declare module 'axe-core/lib/commons/index.js' {
  declare module.exports: $Exports<'axe-core/lib/commons'>;
}
declare module 'axe-core/lib/commons/matches/attributes.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/matches/attributes'>;
}
declare module 'axe-core/lib/commons/matches/condition.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/matches/condition'>;
}
declare module 'axe-core/lib/commons/matches/from-definition.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/matches/from-definition'>;
}
declare module 'axe-core/lib/commons/matches/from-function.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/matches/from-function'>;
}
declare module 'axe-core/lib/commons/matches/from-primative.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/matches/from-primative'>;
}
declare module 'axe-core/lib/commons/matches/index' {
  declare module.exports: $Exports<'axe-core/lib/commons/matches'>;
}
declare module 'axe-core/lib/commons/matches/index.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/matches'>;
}
declare module 'axe-core/lib/commons/matches/node-name.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/matches/node-name'>;
}
declare module 'axe-core/lib/commons/matches/properties.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/matches/properties'>;
}
declare module 'axe-core/lib/commons/table/get-all-cells.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/get-all-cells'>;
}
declare module 'axe-core/lib/commons/table/get-cell-position.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/get-cell-position'>;
}
declare module 'axe-core/lib/commons/table/get-headers.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/get-headers'>;
}
declare module 'axe-core/lib/commons/table/get-scope.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/get-scope'>;
}
declare module 'axe-core/lib/commons/table/index' {
  declare module.exports: $Exports<'axe-core/lib/commons/table'>;
}
declare module 'axe-core/lib/commons/table/index.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table'>;
}
declare module 'axe-core/lib/commons/table/is-column-header.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/is-column-header'>;
}
declare module 'axe-core/lib/commons/table/is-data-cell.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/is-data-cell'>;
}
declare module 'axe-core/lib/commons/table/is-data-table.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/is-data-table'>;
}
declare module 'axe-core/lib/commons/table/is-header.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/is-header'>;
}
declare module 'axe-core/lib/commons/table/is-row-header.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/is-row-header'>;
}
declare module 'axe-core/lib/commons/table/to-grid.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/to-grid'>;
}
declare module 'axe-core/lib/commons/table/traverse.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/table/traverse'>;
}
declare module 'axe-core/lib/commons/text/accessible-text-virtual.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/accessible-text-virtual'>;
}
declare module 'axe-core/lib/commons/text/form-control-value.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/form-control-value'>;
}
declare module 'axe-core/lib/commons/text/index' {
  declare module.exports: $Exports<'axe-core/lib/commons/text'>;
}
declare module 'axe-core/lib/commons/text/index.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text'>;
}
declare module 'axe-core/lib/commons/text/is-human-interpretable.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/is-human-interpretable'>;
}
declare module 'axe-core/lib/commons/text/is-valid-autocomplete.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/is-valid-autocomplete'>;
}
declare module 'axe-core/lib/commons/text/label-text.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/label-text'>;
}
declare module 'axe-core/lib/commons/text/label-virtual.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/label-virtual'>;
}
declare module 'axe-core/lib/commons/text/native-element-types.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/native-element-types'>;
}
declare module 'axe-core/lib/commons/text/native-text-alternative.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/native-text-alternative'>;
}
declare module 'axe-core/lib/commons/text/native-text-methods.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/native-text-methods'>;
}
declare module 'axe-core/lib/commons/text/sanitize.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/sanitize'>;
}
declare module 'axe-core/lib/commons/text/subtree-text.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/subtree-text'>;
}
declare module 'axe-core/lib/commons/text/title-text.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/title-text'>;
}
declare module 'axe-core/lib/commons/text/unicode.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/unicode'>;
}
declare module 'axe-core/lib/commons/text/unsupported.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/unsupported'>;
}
declare module 'axe-core/lib/commons/text/visible-virtual.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/text/visible-virtual'>;
}
declare module 'axe-core/lib/commons/utils/index' {
  declare module.exports: $Exports<'axe-core/lib/commons/utils'>;
}
declare module 'axe-core/lib/commons/utils/index.js' {
  declare module.exports: $Exports<'axe-core/lib/commons/utils'>;
}
declare module 'axe-core/lib/core/base/audit.js' {
  declare module.exports: $Exports<'axe-core/lib/core/base/audit'>;
}
declare module 'axe-core/lib/core/base/cache.js' {
  declare module.exports: $Exports<'axe-core/lib/core/base/cache'>;
}
declare module 'axe-core/lib/core/base/check-result.js' {
  declare module.exports: $Exports<'axe-core/lib/core/base/check-result'>;
}
declare module 'axe-core/lib/core/base/check.js' {
  declare module.exports: $Exports<'axe-core/lib/core/base/check'>;
}
declare module 'axe-core/lib/core/base/context.js' {
  declare module.exports: $Exports<'axe-core/lib/core/base/context'>;
}
declare module 'axe-core/lib/core/base/rule-result.js' {
  declare module.exports: $Exports<'axe-core/lib/core/base/rule-result'>;
}
declare module 'axe-core/lib/core/base/rule.js' {
  declare module.exports: $Exports<'axe-core/lib/core/base/rule'>;
}
declare module 'axe-core/lib/core/base/virtual-node.js' {
  declare module.exports: $Exports<'axe-core/lib/core/base/virtual-node'>;
}
declare module 'axe-core/lib/core/constants.js' {
  declare module.exports: $Exports<'axe-core/lib/core/constants'>;
}
declare module 'axe-core/lib/core/imports/index' {
  declare module.exports: $Exports<'axe-core/lib/core/imports'>;
}
declare module 'axe-core/lib/core/imports/index.js' {
  declare module.exports: $Exports<'axe-core/lib/core/imports'>;
}
declare module 'axe-core/lib/core/index' {
  declare module.exports: $Exports<'axe-core/lib/core'>;
}
declare module 'axe-core/lib/core/index.js' {
  declare module.exports: $Exports<'axe-core/lib/core'>;
}
declare module 'axe-core/lib/core/log.js' {
  declare module.exports: $Exports<'axe-core/lib/core/log'>;
}
declare module 'axe-core/lib/core/public/cleanup-plugins.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/cleanup-plugins'>;
}
declare module 'axe-core/lib/core/public/configure.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/configure'>;
}
declare module 'axe-core/lib/core/public/get-rules.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/get-rules'>;
}
declare module 'axe-core/lib/core/public/load.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/load'>;
}
declare module 'axe-core/lib/core/public/plugins.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/plugins'>;
}
declare module 'axe-core/lib/core/public/reporter.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/reporter'>;
}
declare module 'axe-core/lib/core/public/reset.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/reset'>;
}
declare module 'axe-core/lib/core/public/run-rules.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/run-rules'>;
}
declare module 'axe-core/lib/core/public/run-virtual-rule.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/run-virtual-rule'>;
}
declare module 'axe-core/lib/core/public/run.js' {
  declare module.exports: $Exports<'axe-core/lib/core/public/run'>;
}
declare module 'axe-core/lib/core/reporters/helpers/failure-summary.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/helpers/failure-summary'>;
}
declare module 'axe-core/lib/core/reporters/helpers/get-environment-data.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/helpers/get-environment-data'>;
}
declare module 'axe-core/lib/core/reporters/helpers/incomplete-fallback-msg.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/helpers/incomplete-fallback-msg'>;
}
declare module 'axe-core/lib/core/reporters/helpers/index' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/helpers'>;
}
declare module 'axe-core/lib/core/reporters/helpers/index.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/helpers'>;
}
declare module 'axe-core/lib/core/reporters/helpers/process-aggregate.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/helpers/process-aggregate'>;
}
declare module 'axe-core/lib/core/reporters/na.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/na'>;
}
declare module 'axe-core/lib/core/reporters/no-passes.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/no-passes'>;
}
declare module 'axe-core/lib/core/reporters/raw-env.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/raw-env'>;
}
declare module 'axe-core/lib/core/reporters/raw.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/raw'>;
}
declare module 'axe-core/lib/core/reporters/v1.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/v1'>;
}
declare module 'axe-core/lib/core/reporters/v2.js' {
  declare module.exports: $Exports<'axe-core/lib/core/reporters/v2'>;
}
declare module 'axe-core/lib/core/utils/aggregate.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/aggregate'>;
}
declare module 'axe-core/lib/core/utils/aggregateChecks.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/aggregateChecks'>;
}
declare module 'axe-core/lib/core/utils/aggregateNodeResults.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/aggregateNodeResults'>;
}
declare module 'axe-core/lib/core/utils/aggregateResult.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/aggregateResult'>;
}
declare module 'axe-core/lib/core/utils/are-styles-set.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/are-styles-set'>;
}
declare module 'axe-core/lib/core/utils/check-helper.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/check-helper'>;
}
declare module 'axe-core/lib/core/utils/clone.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/clone'>;
}
declare module 'axe-core/lib/core/utils/collect-results-from-frames.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/collect-results-from-frames'>;
}
declare module 'axe-core/lib/core/utils/contains.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/contains'>;
}
declare module 'axe-core/lib/core/utils/css-parser.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/css-parser'>;
}
declare module 'axe-core/lib/core/utils/dq-element.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/dq-element'>;
}
declare module 'axe-core/lib/core/utils/element-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/element-matches'>;
}
declare module 'axe-core/lib/core/utils/escape-selector.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/escape-selector'>;
}
declare module 'axe-core/lib/core/utils/extend-meta-data.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/extend-meta-data'>;
}
declare module 'axe-core/lib/core/utils/finalize-result.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/finalize-result'>;
}
declare module 'axe-core/lib/core/utils/find-by.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/find-by'>;
}
declare module 'axe-core/lib/core/utils/flattened-tree.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/flattened-tree'>;
}
declare module 'axe-core/lib/core/utils/get-all-checks.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-all-checks'>;
}
declare module 'axe-core/lib/core/utils/get-base-lang.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-base-lang'>;
}
declare module 'axe-core/lib/core/utils/get-check-option.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-check-option'>;
}
declare module 'axe-core/lib/core/utils/get-friendly-uri-end.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-friendly-uri-end'>;
}
declare module 'axe-core/lib/core/utils/get-node-attributes.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-node-attributes'>;
}
declare module 'axe-core/lib/core/utils/get-root-node.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-root-node'>;
}
declare module 'axe-core/lib/core/utils/get-scroll.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-scroll'>;
}
declare module 'axe-core/lib/core/utils/get-selector.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-selector'>;
}
declare module 'axe-core/lib/core/utils/get-stylesheet-factory.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-stylesheet-factory'>;
}
declare module 'axe-core/lib/core/utils/get-xpath.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/get-xpath'>;
}
declare module 'axe-core/lib/core/utils/index' {
  declare module.exports: $Exports<'axe-core/lib/core/utils'>;
}
declare module 'axe-core/lib/core/utils/index.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils'>;
}
declare module 'axe-core/lib/core/utils/inject-style.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/inject-style'>;
}
declare module 'axe-core/lib/core/utils/is-hidden.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/is-hidden'>;
}
declare module 'axe-core/lib/core/utils/is-html-element.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/is-html-element'>;
}
declare module 'axe-core/lib/core/utils/is-shadow-root.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/is-shadow-root'>;
}
declare module 'axe-core/lib/core/utils/is-xhtml.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/is-xhtml'>;
}
declare module 'axe-core/lib/core/utils/merge-results.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/merge-results'>;
}
declare module 'axe-core/lib/core/utils/node-sorter.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/node-sorter'>;
}
declare module 'axe-core/lib/core/utils/parse-crossorigin-stylesheet.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/parse-crossorigin-stylesheet'>;
}
declare module 'axe-core/lib/core/utils/parse-sameorigin-stylesheet.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/parse-sameorigin-stylesheet'>;
}
declare module 'axe-core/lib/core/utils/parse-stylesheet.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/parse-stylesheet'>;
}
declare module 'axe-core/lib/core/utils/performance-timer.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/performance-timer'>;
}
declare module 'axe-core/lib/core/utils/pollyfills.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/pollyfills'>;
}
declare module 'axe-core/lib/core/utils/preload-cssom.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/preload-cssom'>;
}
declare module 'axe-core/lib/core/utils/preload.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/preload'>;
}
declare module 'axe-core/lib/core/utils/publish-metadata.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/publish-metadata'>;
}
declare module 'axe-core/lib/core/utils/qsa.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/qsa'>;
}
declare module 'axe-core/lib/core/utils/queue.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/queue'>;
}
declare module 'axe-core/lib/core/utils/respondable.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/respondable'>;
}
declare module 'axe-core/lib/core/utils/rule-should-run.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/rule-should-run'>;
}
declare module 'axe-core/lib/core/utils/scroll-state.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/scroll-state'>;
}
declare module 'axe-core/lib/core/utils/select.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/select'>;
}
declare module 'axe-core/lib/core/utils/to-array.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/to-array'>;
}
declare module 'axe-core/lib/core/utils/token-list.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/token-list'>;
}
declare module 'axe-core/lib/core/utils/uuid.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/uuid'>;
}
declare module 'axe-core/lib/core/utils/valid-input-type.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/valid-input-type'>;
}
declare module 'axe-core/lib/core/utils/valid-langs.js' {
  declare module.exports: $Exports<'axe-core/lib/core/utils/valid-langs'>;
}
declare module 'axe-core/lib/rules/aria-allowed-attr-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/aria-allowed-attr-matches'>;
}
declare module 'axe-core/lib/rules/aria-allowed-role-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/aria-allowed-role-matches'>;
}
declare module 'axe-core/lib/rules/aria-dpub-role-fallback-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/aria-dpub-role-fallback-matches'>;
}
declare module 'axe-core/lib/rules/aria-form-field-name-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/aria-form-field-name-matches'>;
}
declare module 'axe-core/lib/rules/aria-has-attr-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/aria-has-attr-matches'>;
}
declare module 'axe-core/lib/rules/aria-hidden-focus-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/aria-hidden-focus-matches'>;
}
declare module 'axe-core/lib/rules/autocomplete-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/autocomplete-matches'>;
}
declare module 'axe-core/lib/rules/bypass-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/bypass-matches'>;
}
declare module 'axe-core/lib/rules/color-contrast-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/color-contrast-matches'>;
}
declare module 'axe-core/lib/rules/data-table-large-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/data-table-large-matches'>;
}
declare module 'axe-core/lib/rules/data-table-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/data-table-matches'>;
}
declare module 'axe-core/lib/rules/duplicate-id-active-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/duplicate-id-active-matches'>;
}
declare module 'axe-core/lib/rules/duplicate-id-aria-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/duplicate-id-aria-matches'>;
}
declare module 'axe-core/lib/rules/duplicate-id-misc-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/duplicate-id-misc-matches'>;
}
declare module 'axe-core/lib/rules/frame-title-has-text.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/frame-title-has-text'>;
}
declare module 'axe-core/lib/rules/heading-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/heading-matches'>;
}
declare module 'axe-core/lib/rules/inserted-into-focus-order-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/inserted-into-focus-order-matches'>;
}
declare module 'axe-core/lib/rules/label-content-name-mismatch-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/label-content-name-mismatch-matches'>;
}
declare module 'axe-core/lib/rules/label-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/label-matches'>;
}
declare module 'axe-core/lib/rules/landmark-has-body-context.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/landmark-has-body-context'>;
}
declare module 'axe-core/lib/rules/landmark-unique-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/landmark-unique-matches'>;
}
declare module 'axe-core/lib/rules/layout-table-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/layout-table-matches'>;
}
declare module 'axe-core/lib/rules/link-in-text-block-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/link-in-text-block-matches'>;
}
declare module 'axe-core/lib/rules/no-role-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/no-role-matches'>;
}
declare module 'axe-core/lib/rules/not-html-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/not-html-matches'>;
}
declare module 'axe-core/lib/rules/p-as-heading-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/p-as-heading-matches'>;
}
declare module 'axe-core/lib/rules/role-not-button-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/role-not-button-matches'>;
}
declare module 'axe-core/lib/rules/scrollable-region-focusable-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/scrollable-region-focusable-matches'>;
}
declare module 'axe-core/lib/rules/skip-link-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/skip-link-matches'>;
}
declare module 'axe-core/lib/rules/window-is-top.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/window-is-top'>;
}
declare module 'axe-core/lib/rules/xml-lang-mismatch-matches.js' {
  declare module.exports: $Exports<'axe-core/lib/rules/xml-lang-mismatch-matches'>;
}
