// flow-typed signature: 69ddec7334011111581800dca07fad3f
// flow-typed version: <<STUB>>/fomantic-ui_v^2.7.7/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fomantic-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fomantic-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fomantic-ui/dist/components/accordion' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/accordion.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/api' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/api.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/calendar' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/calendar.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/checkbox' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/checkbox.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/dimmer' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/dimmer.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/dropdown' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/dropdown.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/embed' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/embed.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/form' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/form.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/modal' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/modal.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/nag' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/nag.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/popup' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/popup.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/progress' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/progress.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/range' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/range.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/rating' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/rating.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/search' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/search.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/shape' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/shape.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/sidebar' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/sidebar.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/site' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/site.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/slider' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/slider.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/state' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/state.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/sticky' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/sticky.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/tab' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/tab.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/toast' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/toast.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/transition' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/transition.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/visibility' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/components/visibility.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/semantic' {
  declare module.exports: any;
}

declare module 'fomantic-ui/dist/semantic.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/examples/assets/library/iframe-content' {
  declare module.exports: any;
}

declare module 'fomantic-ui/examples/assets/library/iframe' {
  declare module.exports: any;
}

declare module 'fomantic-ui/examples/assets/library/jquery.min' {
  declare module.exports: any;
}

declare module 'fomantic-ui/examples/assets/show-examples' {
  declare module.exports: any;
}

declare module 'fomantic-ui/gulpfile' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/behaviors/api' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/behaviors/form' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/behaviors/state' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/behaviors/visibility' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/globals/site' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/accordion' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/calendar' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/checkbox' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/dimmer' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/dropdown' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/embed' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/modal' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/nag' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/popup' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/progress' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/rating' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/search' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/shape' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/sidebar' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/slider' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/sticky' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/tab' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/toast' {
  declare module.exports: any;
}

declare module 'fomantic-ui/src/definitions/modules/transition' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/admin/components/create' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/admin/components/init' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/admin/components/update' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/admin/distributions/create' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/admin/distributions/init' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/admin/distributions/update' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/admin/publish' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/admin/register' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/admin/release' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/build' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/build/assets' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/build/css' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/build/javascript' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/check-install' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/clean' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/collections/admin' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/collections/build' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/collections/docs' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/collections/install' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/collections/rtl' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/collections/various' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/admin/github' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/admin/oauth.example' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/admin/release' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/admin/templates/component-package' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/admin/templates/css-package' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/admin/templates/less-package' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/defaults' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/docs' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/npm/gulpfile' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/project/config' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/project/install' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/project/release' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/tasks' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/config/user' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/docs/build' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/docs/metadata' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/docs/serve' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/install' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/rtl/build' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/rtl/watch' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/version' {
  declare module.exports: any;
}

declare module 'fomantic-ui/tasks/watch' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/helpers/jasmine-clog' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/helpers/jasmine-jquery' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/helpers/jasmine-sinon' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/helpers/jquery-events' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/helpers/sinon' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/meteor/assets' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/meteor/fonts' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/accordion.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/checkbox.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/dropdown.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/modal.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/module.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/popup.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/search.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/shape.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/sidebar.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/tab.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/transition.spec' {
  declare module.exports: any;
}

declare module 'fomantic-ui/test/modules/video.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fomantic-ui/dist/components/accordion.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/accordion'>;
}
declare module 'fomantic-ui/dist/components/accordion.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/accordion.min'>;
}
declare module 'fomantic-ui/dist/components/api.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/api'>;
}
declare module 'fomantic-ui/dist/components/api.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/api.min'>;
}
declare module 'fomantic-ui/dist/components/calendar.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/calendar'>;
}
declare module 'fomantic-ui/dist/components/calendar.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/calendar.min'>;
}
declare module 'fomantic-ui/dist/components/checkbox.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/checkbox'>;
}
declare module 'fomantic-ui/dist/components/checkbox.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/checkbox.min'>;
}
declare module 'fomantic-ui/dist/components/dimmer.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/dimmer'>;
}
declare module 'fomantic-ui/dist/components/dimmer.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/dimmer.min'>;
}
declare module 'fomantic-ui/dist/components/dropdown.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/dropdown'>;
}
declare module 'fomantic-ui/dist/components/dropdown.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/dropdown.min'>;
}
declare module 'fomantic-ui/dist/components/embed.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/embed'>;
}
declare module 'fomantic-ui/dist/components/embed.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/embed.min'>;
}
declare module 'fomantic-ui/dist/components/form.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/form'>;
}
declare module 'fomantic-ui/dist/components/form.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/form.min'>;
}
declare module 'fomantic-ui/dist/components/modal.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/modal'>;
}
declare module 'fomantic-ui/dist/components/modal.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/modal.min'>;
}
declare module 'fomantic-ui/dist/components/nag.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/nag'>;
}
declare module 'fomantic-ui/dist/components/nag.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/nag.min'>;
}
declare module 'fomantic-ui/dist/components/popup.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/popup'>;
}
declare module 'fomantic-ui/dist/components/popup.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/popup.min'>;
}
declare module 'fomantic-ui/dist/components/progress.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/progress'>;
}
declare module 'fomantic-ui/dist/components/progress.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/progress.min'>;
}
declare module 'fomantic-ui/dist/components/range.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/range'>;
}
declare module 'fomantic-ui/dist/components/range.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/range.min'>;
}
declare module 'fomantic-ui/dist/components/rating.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/rating'>;
}
declare module 'fomantic-ui/dist/components/rating.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/rating.min'>;
}
declare module 'fomantic-ui/dist/components/search.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/search'>;
}
declare module 'fomantic-ui/dist/components/search.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/search.min'>;
}
declare module 'fomantic-ui/dist/components/shape.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/shape'>;
}
declare module 'fomantic-ui/dist/components/shape.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/shape.min'>;
}
declare module 'fomantic-ui/dist/components/sidebar.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/sidebar'>;
}
declare module 'fomantic-ui/dist/components/sidebar.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/sidebar.min'>;
}
declare module 'fomantic-ui/dist/components/site.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/site'>;
}
declare module 'fomantic-ui/dist/components/site.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/site.min'>;
}
declare module 'fomantic-ui/dist/components/slider.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/slider'>;
}
declare module 'fomantic-ui/dist/components/slider.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/slider.min'>;
}
declare module 'fomantic-ui/dist/components/state.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/state'>;
}
declare module 'fomantic-ui/dist/components/state.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/state.min'>;
}
declare module 'fomantic-ui/dist/components/sticky.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/sticky'>;
}
declare module 'fomantic-ui/dist/components/sticky.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/sticky.min'>;
}
declare module 'fomantic-ui/dist/components/tab.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/tab'>;
}
declare module 'fomantic-ui/dist/components/tab.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/tab.min'>;
}
declare module 'fomantic-ui/dist/components/toast.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/toast'>;
}
declare module 'fomantic-ui/dist/components/toast.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/toast.min'>;
}
declare module 'fomantic-ui/dist/components/transition.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/transition'>;
}
declare module 'fomantic-ui/dist/components/transition.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/transition.min'>;
}
declare module 'fomantic-ui/dist/components/visibility.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/visibility'>;
}
declare module 'fomantic-ui/dist/components/visibility.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/components/visibility.min'>;
}
declare module 'fomantic-ui/dist/semantic.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/semantic'>;
}
declare module 'fomantic-ui/dist/semantic.min.js' {
  declare module.exports: $Exports<'fomantic-ui/dist/semantic.min'>;
}
declare module 'fomantic-ui/examples/assets/library/iframe-content.js' {
  declare module.exports: $Exports<'fomantic-ui/examples/assets/library/iframe-content'>;
}
declare module 'fomantic-ui/examples/assets/library/iframe.js' {
  declare module.exports: $Exports<'fomantic-ui/examples/assets/library/iframe'>;
}
declare module 'fomantic-ui/examples/assets/library/jquery.min.js' {
  declare module.exports: $Exports<'fomantic-ui/examples/assets/library/jquery.min'>;
}
declare module 'fomantic-ui/examples/assets/show-examples.js' {
  declare module.exports: $Exports<'fomantic-ui/examples/assets/show-examples'>;
}
declare module 'fomantic-ui/gulpfile.js' {
  declare module.exports: $Exports<'fomantic-ui/gulpfile'>;
}
declare module 'fomantic-ui/src/definitions/behaviors/api.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/behaviors/api'>;
}
declare module 'fomantic-ui/src/definitions/behaviors/form.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/behaviors/form'>;
}
declare module 'fomantic-ui/src/definitions/behaviors/state.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/behaviors/state'>;
}
declare module 'fomantic-ui/src/definitions/behaviors/visibility.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/behaviors/visibility'>;
}
declare module 'fomantic-ui/src/definitions/globals/site.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/globals/site'>;
}
declare module 'fomantic-ui/src/definitions/modules/accordion.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/accordion'>;
}
declare module 'fomantic-ui/src/definitions/modules/calendar.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/calendar'>;
}
declare module 'fomantic-ui/src/definitions/modules/checkbox.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/checkbox'>;
}
declare module 'fomantic-ui/src/definitions/modules/dimmer.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/dimmer'>;
}
declare module 'fomantic-ui/src/definitions/modules/dropdown.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/dropdown'>;
}
declare module 'fomantic-ui/src/definitions/modules/embed.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/embed'>;
}
declare module 'fomantic-ui/src/definitions/modules/modal.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/modal'>;
}
declare module 'fomantic-ui/src/definitions/modules/nag.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/nag'>;
}
declare module 'fomantic-ui/src/definitions/modules/popup.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/popup'>;
}
declare module 'fomantic-ui/src/definitions/modules/progress.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/progress'>;
}
declare module 'fomantic-ui/src/definitions/modules/rating.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/rating'>;
}
declare module 'fomantic-ui/src/definitions/modules/search.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/search'>;
}
declare module 'fomantic-ui/src/definitions/modules/shape.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/shape'>;
}
declare module 'fomantic-ui/src/definitions/modules/sidebar.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/sidebar'>;
}
declare module 'fomantic-ui/src/definitions/modules/slider.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/slider'>;
}
declare module 'fomantic-ui/src/definitions/modules/sticky.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/sticky'>;
}
declare module 'fomantic-ui/src/definitions/modules/tab.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/tab'>;
}
declare module 'fomantic-ui/src/definitions/modules/toast.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/toast'>;
}
declare module 'fomantic-ui/src/definitions/modules/transition.js' {
  declare module.exports: $Exports<'fomantic-ui/src/definitions/modules/transition'>;
}
declare module 'fomantic-ui/tasks/admin/components/create.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/admin/components/create'>;
}
declare module 'fomantic-ui/tasks/admin/components/init.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/admin/components/init'>;
}
declare module 'fomantic-ui/tasks/admin/components/update.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/admin/components/update'>;
}
declare module 'fomantic-ui/tasks/admin/distributions/create.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/admin/distributions/create'>;
}
declare module 'fomantic-ui/tasks/admin/distributions/init.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/admin/distributions/init'>;
}
declare module 'fomantic-ui/tasks/admin/distributions/update.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/admin/distributions/update'>;
}
declare module 'fomantic-ui/tasks/admin/publish.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/admin/publish'>;
}
declare module 'fomantic-ui/tasks/admin/register.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/admin/register'>;
}
declare module 'fomantic-ui/tasks/admin/release.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/admin/release'>;
}
declare module 'fomantic-ui/tasks/build.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/build'>;
}
declare module 'fomantic-ui/tasks/build/assets.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/build/assets'>;
}
declare module 'fomantic-ui/tasks/build/css.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/build/css'>;
}
declare module 'fomantic-ui/tasks/build/javascript.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/build/javascript'>;
}
declare module 'fomantic-ui/tasks/check-install.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/check-install'>;
}
declare module 'fomantic-ui/tasks/clean.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/clean'>;
}
declare module 'fomantic-ui/tasks/collections/admin.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/collections/admin'>;
}
declare module 'fomantic-ui/tasks/collections/build.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/collections/build'>;
}
declare module 'fomantic-ui/tasks/collections/docs.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/collections/docs'>;
}
declare module 'fomantic-ui/tasks/collections/install.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/collections/install'>;
}
declare module 'fomantic-ui/tasks/collections/rtl.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/collections/rtl'>;
}
declare module 'fomantic-ui/tasks/collections/various.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/collections/various'>;
}
declare module 'fomantic-ui/tasks/config/admin/github.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/admin/github'>;
}
declare module 'fomantic-ui/tasks/config/admin/oauth.example.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/admin/oauth.example'>;
}
declare module 'fomantic-ui/tasks/config/admin/release.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/admin/release'>;
}
declare module 'fomantic-ui/tasks/config/admin/templates/component-package.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/admin/templates/component-package'>;
}
declare module 'fomantic-ui/tasks/config/admin/templates/css-package.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/admin/templates/css-package'>;
}
declare module 'fomantic-ui/tasks/config/admin/templates/less-package.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/admin/templates/less-package'>;
}
declare module 'fomantic-ui/tasks/config/defaults.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/defaults'>;
}
declare module 'fomantic-ui/tasks/config/docs.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/docs'>;
}
declare module 'fomantic-ui/tasks/config/npm/gulpfile.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/npm/gulpfile'>;
}
declare module 'fomantic-ui/tasks/config/project/config.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/project/config'>;
}
declare module 'fomantic-ui/tasks/config/project/install.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/project/install'>;
}
declare module 'fomantic-ui/tasks/config/project/release.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/project/release'>;
}
declare module 'fomantic-ui/tasks/config/tasks.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/tasks'>;
}
declare module 'fomantic-ui/tasks/config/user.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/config/user'>;
}
declare module 'fomantic-ui/tasks/docs/build.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/docs/build'>;
}
declare module 'fomantic-ui/tasks/docs/metadata.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/docs/metadata'>;
}
declare module 'fomantic-ui/tasks/docs/serve.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/docs/serve'>;
}
declare module 'fomantic-ui/tasks/install.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/install'>;
}
declare module 'fomantic-ui/tasks/rtl/build.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/rtl/build'>;
}
declare module 'fomantic-ui/tasks/rtl/watch.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/rtl/watch'>;
}
declare module 'fomantic-ui/tasks/version.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/version'>;
}
declare module 'fomantic-ui/tasks/watch.js' {
  declare module.exports: $Exports<'fomantic-ui/tasks/watch'>;
}
declare module 'fomantic-ui/test/helpers/jasmine-clog.js' {
  declare module.exports: $Exports<'fomantic-ui/test/helpers/jasmine-clog'>;
}
declare module 'fomantic-ui/test/helpers/jasmine-jquery.js' {
  declare module.exports: $Exports<'fomantic-ui/test/helpers/jasmine-jquery'>;
}
declare module 'fomantic-ui/test/helpers/jasmine-sinon.js' {
  declare module.exports: $Exports<'fomantic-ui/test/helpers/jasmine-sinon'>;
}
declare module 'fomantic-ui/test/helpers/jquery-events.js' {
  declare module.exports: $Exports<'fomantic-ui/test/helpers/jquery-events'>;
}
declare module 'fomantic-ui/test/helpers/sinon.js' {
  declare module.exports: $Exports<'fomantic-ui/test/helpers/sinon'>;
}
declare module 'fomantic-ui/test/meteor/assets.js' {
  declare module.exports: $Exports<'fomantic-ui/test/meteor/assets'>;
}
declare module 'fomantic-ui/test/meteor/fonts.js' {
  declare module.exports: $Exports<'fomantic-ui/test/meteor/fonts'>;
}
declare module 'fomantic-ui/test/modules/accordion.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/accordion.spec'>;
}
declare module 'fomantic-ui/test/modules/checkbox.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/checkbox.spec'>;
}
declare module 'fomantic-ui/test/modules/dropdown.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/dropdown.spec'>;
}
declare module 'fomantic-ui/test/modules/modal.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/modal.spec'>;
}
declare module 'fomantic-ui/test/modules/module.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/module.spec'>;
}
declare module 'fomantic-ui/test/modules/popup.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/popup.spec'>;
}
declare module 'fomantic-ui/test/modules/search.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/search.spec'>;
}
declare module 'fomantic-ui/test/modules/shape.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/shape.spec'>;
}
declare module 'fomantic-ui/test/modules/sidebar.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/sidebar.spec'>;
}
declare module 'fomantic-ui/test/modules/tab.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/tab.spec'>;
}
declare module 'fomantic-ui/test/modules/transition.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/transition.spec'>;
}
declare module 'fomantic-ui/test/modules/video.spec.js' {
  declare module.exports: $Exports<'fomantic-ui/test/modules/video.spec'>;
}
