// flow-typed signature: de54c559908edcc3e398e2eda85a1703
// flow-typed version: <<STUB>>/generator-mnml-component_v0.0.6/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generator-mnml-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generator-mnml-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generator-mnml-component/app' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-Presenter/__tests__/<%= componentName %>Container.spec' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-Presenter/__tests__/<%= componentName %>Presenter.spec' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-Presenter/<%= componentName %>Container' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-Presenter/<%= componentName %>Presenter' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-Presenter' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/__tests__/<%= componentName %>Container.spec' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/__tests__/<%= componentName %>Presenter.spec' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/__tests__/<%= componentName %>WithState.spec' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/<%= componentName %>Container' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/<%= componentName %>Presenter' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/<%= componentName %>WithState' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Presenter/__tests__/<%= componentName %>Presenter.spec' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Presenter/<%= componentName %>Presenter' {
  declare module.exports: any;
}

declare module 'generator-mnml-component/app/templates/Presenter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generator-mnml-component/app/index' {
  declare module.exports: $Exports<'generator-mnml-component/app'>;
}
declare module 'generator-mnml-component/app/index.js' {
  declare module.exports: $Exports<'generator-mnml-component/app'>;
}
declare module 'generator-mnml-component/app/templates/Container-Presenter/__tests__/<%= componentName %>Container.spec.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-Presenter/__tests__/<%= componentName %>Container.spec'>;
}
declare module 'generator-mnml-component/app/templates/Container-Presenter/__tests__/<%= componentName %>Presenter.spec.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-Presenter/__tests__/<%= componentName %>Presenter.spec'>;
}
declare module 'generator-mnml-component/app/templates/Container-Presenter/<%= componentName %>Container.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-Presenter/<%= componentName %>Container'>;
}
declare module 'generator-mnml-component/app/templates/Container-Presenter/<%= componentName %>Presenter.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-Presenter/<%= componentName %>Presenter'>;
}
declare module 'generator-mnml-component/app/templates/Container-Presenter/index' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-Presenter'>;
}
declare module 'generator-mnml-component/app/templates/Container-Presenter/index.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-Presenter'>;
}
declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/__tests__/<%= componentName %>Container.spec.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-WithState-Presenter/__tests__/<%= componentName %>Container.spec'>;
}
declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/__tests__/<%= componentName %>Presenter.spec.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-WithState-Presenter/__tests__/<%= componentName %>Presenter.spec'>;
}
declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/__tests__/<%= componentName %>WithState.spec.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-WithState-Presenter/__tests__/<%= componentName %>WithState.spec'>;
}
declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/<%= componentName %>Container.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-WithState-Presenter/<%= componentName %>Container'>;
}
declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/<%= componentName %>Presenter.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-WithState-Presenter/<%= componentName %>Presenter'>;
}
declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/<%= componentName %>WithState.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-WithState-Presenter/<%= componentName %>WithState'>;
}
declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/index' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-WithState-Presenter'>;
}
declare module 'generator-mnml-component/app/templates/Container-WithState-Presenter/index.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Container-WithState-Presenter'>;
}
declare module 'generator-mnml-component/app/templates/Presenter/__tests__/<%= componentName %>Presenter.spec.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Presenter/__tests__/<%= componentName %>Presenter.spec'>;
}
declare module 'generator-mnml-component/app/templates/Presenter/<%= componentName %>Presenter.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Presenter/<%= componentName %>Presenter'>;
}
declare module 'generator-mnml-component/app/templates/Presenter/index' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Presenter'>;
}
declare module 'generator-mnml-component/app/templates/Presenter/index.js' {
  declare module.exports: $Exports<'generator-mnml-component/app/templates/Presenter'>;
}
