// flow-typed signature: 561f9ce4351664bac278281e2f38c149
// flow-typed version: <<STUB>>/mo-js_v^0.288.2/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mo-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mo-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mo-js/build/mo' {
  declare module.exports: any;
}

declare module 'mo-js/build/mo.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mo-js/build/mo.js' {
  declare module.exports: $Exports<'mo-js/build/mo'>;
}
declare module 'mo-js/build/mo.min.js' {
  declare module.exports: $Exports<'mo-js/build/mo.min'>;
}
