// flow-typed signature: 1127640be454a4aeeda4a6ea16aeecc0
// flow-typed version: <<STUB>>/react-thunk_v^1.0.0/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-thunk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-thunk/dist/commonjs' {
  declare module.exports: any;
}

declare module 'react-thunk/dist/es' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-thunk/dist/commonjs/index' {
  declare module.exports: $Exports<'react-thunk/dist/commonjs'>;
}
declare module 'react-thunk/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-thunk/dist/commonjs'>;
}
declare module 'react-thunk/dist/es/index' {
  declare module.exports: $Exports<'react-thunk/dist/es'>;
}
declare module 'react-thunk/dist/es/index.js' {
  declare module.exports: $Exports<'react-thunk/dist/es'>;
}
