// flow-typed signature: ea5e2110bf5952a6f0c8e0f114fe38d3
// flow-typed version: <<STUB>>/@svgr/cli_v^4.3.2/flow_v0.103.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/cli/lib/dirCommand' {
  declare module.exports: any;
}

declare module '@svgr/cli/lib/fileCommand' {
  declare module.exports: any;
}

declare module '@svgr/cli/lib' {
  declare module.exports: any;
}

declare module '@svgr/cli/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/cli/lib/dirCommand.js' {
  declare module.exports: $Exports<'@svgr/cli/lib/dirCommand'>;
}
declare module '@svgr/cli/lib/fileCommand.js' {
  declare module.exports: $Exports<'@svgr/cli/lib/fileCommand'>;
}
declare module '@svgr/cli/lib/index' {
  declare module.exports: $Exports<'@svgr/cli/lib'>;
}
declare module '@svgr/cli/lib/index.js' {
  declare module.exports: $Exports<'@svgr/cli/lib'>;
}
declare module '@svgr/cli/lib/util.js' {
  declare module.exports: $Exports<'@svgr/cli/lib/util'>;
}
